"""is active columns for bots

Revision ID: 08f4711a7745
Revises: ef81002bc076
Create Date: 2024-06-13 09:46:11.955444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f4711a7745'
down_revision: Union[str, None] = 'ef81002bc076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'is_active')
    # ### end Alembic commands ###
