"""message add sub

Revision ID: 3b6dcb8e755a
Revises: f83da55072b8
Create Date: 2024-06-26 11:18:29.863925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6dcb8e755a'
down_revision: Union[str, None] = 'f83da55072b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'subject')
    # ### end Alembic commands ###
