"""add_messages

Revision ID: d9217c322f25
Revises: 23b909804158
Create Date: 2024-06-14 16:14:15.722005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9217c322f25'
down_revision: Union[str, None] = '23b909804158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sendingmessages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_message', sa.Integer(), nullable=True),
    sa.Column('sender_bot_id', sa.Integer(), nullable=True),
    sa.Column('recipients', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sending_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_message'], ['message.id'], ),
    sa.ForeignKeyConstraint(['sender_bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sendingmessages_id'), 'sendingmessages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sendingmessages_id'), table_name='sendingmessages')
    op.drop_table('sendingmessages')
    op.drop_table('message')
    # ### end Alembic commands ###
